#!/usr/bin/env node
// kb/build-kb.js — Builds kb/kb.js from all markdown files in avaamo-kb/
// Run: node kb/build-kb.js

const fs   = require('fs');
const path = require('path');

const KB_DIR    = path.join(__dirname, '..', 'avaamo-kb');
const OUT_FILE  = path.join(__dirname, '..', 'kb.js');
const CHUNK_SIZE    = 600;  // characters per chunk
const CHUNK_OVERLAP = 80;   // overlap between chunks

function getCategory(filePath) {
  const parts = filePath.split(path.sep);
  const kbIdx = parts.indexOf('avaamo-kb');
  return kbIdx !== -1 && parts[kbIdx + 1] ? parts[kbIdx + 1] : 'other';
}

function chunkText(text, size, overlap) {
  const chunks = [];
  let start = 0;
  while (start < text.length) {
    chunks.push(text.slice(start, start + size));
    start += size - overlap;
  }
  return chunks;
}

function extractTopic(content, filename) {
  const headingMatch = content.match(/^#+\s+(.+)/m);
  if (headingMatch) return headingMatch[1].trim();
  return path.basename(filename, '.md').replace(/-/g, ' ');
}

function walkDir(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...walkDir(full));
    else if (entry.name.endsWith('.md')) results.push(full);
  }
  return results;
}

const files = walkDir(KB_DIR);
const allChunks = [];

for (const file of files) {
  const content  = fs.readFileSync(file, 'utf8');
  const topic    = extractTopic(content, file);
  const category = getCategory(file);
  const filename = path.basename(file);
  const chunks   = chunkText(content, CHUNK_SIZE, CHUNK_OVERLAP);

  chunks.forEach((chunk, i) => {
    allChunks.push({
      topic,
      content: chunk,
      source:  filename,
      folder:  category,
      chunk:   chunks.length > 1 ? i + 1 : null
    });
  });
}

const output = `// Auto-generated by kb/build-kb.js — run 'node kb/build-kb.js' to regenerate
// Generated: ${new Date().toISOString()} | ${allChunks.length} chunks from ${files.length} files
const AVAAMO_KB_CHUNKS = ${JSON.stringify(allChunks, null, 2)};
`;

fs.writeFileSync(OUT_FILE, output, 'utf8');
console.log(`✅ Built ${allChunks.length} chunks from ${files.length} files → kb.js`);
